[tool.poetry]
name = "fact-check"
version = "0.1.0"
description = ""
authors = ["Felix Mönckemeyer <felix.moenckemeyer@rwth-aachen.de>"]
license = "MIT"
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.11"
python-dotenv = "^1.0.1"
gpt-json = "^0.4.2"
newspaper3k = "^0.2.8"
pytablewriter = "^1.2.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
